apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-reverse-proxy
  namespace: osc
  labels:
    app.kubernetes.io/instance: app-reverse-proxy
    app.kubernetes.io/name: app-reverse-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  tls:
    - secretName: app-mydomain-com-tls
      hosts:
        - metadata.opensciencedata.esa.int
  rules:
  - host: metadata.opensciencedata.esa.int
    http:
      paths:
      - path: /
        backend:
          serviceName: app-reverse-proxy
          servicePort: http
