{{ if .Values.domain.proc.enabled }}
{{ if .Values.nfs.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eoepca-proc-pv
  labels:
    eoepca-type: proc
spec:
  storageClassName: {{ .Values.nfs.storageClass }}
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: {{ .Values.nfs.server.address }}
    path: /data/proc
{{ end }}
{{ if .Values.host.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eoepca-proc-pv-host
  labels:
    eoepca-type: proc
spec:
  storageClassName: {{ .Values.host.storageClass }}
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /kubedata/proc
    type: DirectoryOrCreate
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eoepca-proc-pvc
  labels:
    eoepca-type: proc
spec:
  storageClassName: {{ .Values.domain.proc.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      eoepca-type: proc
{{ end }}
