
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gluu-ingress-pep-engine
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.global.ep | quote }}
    http:
      paths:
      - path: /secure(/|$)(.*)
        backend:
          serviceName: pep-engine
          servicePort: 5566
  
