---
# Source: vs/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rm-registration-endpoint
  namespace: rm-user1
  labels:
    helm.sh/chart: vs-0.3.14
    app.kubernetes.io/name: vs
    app.kubernetes.io/instance: vs-s2
    app.kubernetes.io/version: "1.1.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - "data-access-user.demo.eoepca.org"
      secretName: data-access-tls
  rules:
    - host: "data-access-user.demo.eoepca.org"
      http:
        paths:
          - path: /registration/(.*)
            backend:
              serviceName: rm-registration-endpoint
              servicePort: http
