apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notification-controller
  namespace: flux-system
  annotations:
    kubernetes.io/elb.ip: 80.158.53.207
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - notification-controller.80.158.53.207.nip.io
      secretName: notification-controller-tls
  rules:
  - host: notification-controller.80.158.53.207.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: notification-controller-webhook
          servicePort: 80
