apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-science-catalog-backend
  namespace: rm
  labels:
    app.kubernetes.io/instance: open-science-catalog-backend
    app.kubernetes.io/name: open-science-catalog-backend
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-science-catalog-backend
      app.kubernetes.io/name: open-science-catalog-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: open-science-catalog-backend
        app.kubernetes.io/name: open-science-catalog-backend
    spec:
      containers:
      - name: open-science-catalog-backend
        image: 'eoepca/open-science-catalog-backend:0.0.1'
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /probe
            port: 8080
        livenessProbe:
          httpGet:
            path: /probe
            port: 8080
        env:
        - name: GITHUB_REPO_ID
          value: totycro/stacs
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: open-science-catalog-backend-git
              key: token
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi
          requests:
            cpu: 0.2
            memory: 256Mi
      imagePullSecrets:
      - name: flux-open-science-catalog-backend
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
