apiVersion: v1
kind: PersistentVolume
metadata:
  name: eoepca-pdp-pv-host
  labels:
    eoepca_type: userman
spec:
  capacity:
    storage: {{ .Values.persistence.dbStorageSize }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  hostPath:
    path: "/kubedata/userman"
    type: {{ .Values.persistence.type }}