apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-science-catalog-frontend
  namespace: rm
  labels:
    app.kubernetes.io/instance: open-science-catalog-frontend
    app.kubernetes.io/name: open-science-catalog-frontend
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-science-catalog-frontend
      app.kubernetes.io/name: open-science-catalog-frontend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: open-science-catalog-frontend
        app.kubernetes.io/name: open-science-catalog-frontend
    spec:
      containers:
      - name: open-science-catalog-frontend
        image: 'eoepca/open-science-catalog-frontend:v1.0.1'
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        env:
        - name: STATIC_ENDPOINT
          value: https://metadata.osc.develop.eoepca.org/open-science-catalog-metadata/
        - name: DYNAMIC_ENDPOINT
          value: https://resource-catalogue.osc.develop.eoepca.org
        - name: BACKEND_ENDPOINT
          value: https://open-science-catalog-backend.develop.eoepca.org
        - name: OPENID_CONFIGURATION
          value: https://auth.develop.eoepca.org/.well-known/openid-configuration
        - name: OAUTH_CLIENTID
          value: 2af21e66-bd47-4894-b91e-2f3d6c07d99e
        - name: OAUTH_SCOPE
          value: profile email
        - name: OAUTH_REDIRECT_LOGOUT
          value: /
        - name: OAUTH_REDIRECT_CALLBACK
          value: /oauth-callback
        - name: ENABLE_AUTH
          value: "false"
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi
          requests:
            cpu: 0.2
            memory: 256Mi
      imagePullSecrets:
      - name: flux-open-science-catalog-frontend
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
