name: Test workflow

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Name the Job
    name: Test the deployment and acceptance tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install ubuntu dependencies
        run: sudo apt-get install jq python3-venv
      - name: Install kubectl
        run: ./bin/install-kubectl.sh
      - name: Install minikube
        run: ./minikube/setup-minikube_GITHUB.sh github
      - name: Install terraform
        run: ./bin/install-terraform.sh
      - name: Deploy EOEPCA
        run: ./terraform/test/deployEOEPCA_GITHUB.sh
      - name: Run acceptance tests
        run: ./test/acceptance/acceptance_tests.sh
