apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: resource-catalogue
  namespace: rm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
  - host: resource-catalogue.test.185.52.193.87.nip.io
    http:
      paths:
      - backend:
          serviceName: resource-catalogue-service
          servicePort: http
  tls:
    - hosts:
      - ressource-catalogue.185.52.193.87.nip.io
      secretName: ressource-catalogue-tls