apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rm
  labels:
    io.kompose.service: pycsw
  name: resource-catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pycsw
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: pycsw
    spec:
      containers:
      - env:
        - name: PYCSW_SERVER_URL
          value: http://resource-catalogue.test.185.52.193.87.nip.io/
        - name: PYCSW_REPOSITORY_DATABASE_URI
          value: postgresql://postgres:mypass@resource-catalogue-db/pycsw
        image: 'geopython/pycsw:latest'
        name: pycsw
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /etc/pycsw
          name: resource-catalogue-config
      restartPolicy: Always
      volumes:
      - name: resource-catalogue-config
        configMap:
          name: resource-catalogue-configmap
